### PR TITLE
Language picker

### PR DESCRIPTION
**Pull request by mintsitecore**

### CODE REVIEW

**Comment by scottmulligan** [comment]
After reviewing languages, I don't think this is something we can push out to the Sales Engineers at this time. The set up for languages is quite complex and requires many configuration steps each time a new language is added.

I am disappointed with the language capabilities in the product for static headless sites. Let's follow up internally to get some more info on best practices when working with languages.

**Comment by scottmulligan** [comment]
Notes to look at:
- Language picker dropdown always set to English after page reload instead of setting context language
- Can't figure out how to get language fallback to work (attempted to add fallback setting to site definition but no luck)

**Review by mintsitecore — COMMENTED** [review]
looks good

**Comment by scottmulligan** [comment]
I think we are in a good spot to approve this PR to develop and run some final tests against SHOP. The language is set to not show in the URL for "en" and should not effect SHOP.

**Review by scottmulligan — APPROVED** [review]
Huge effort on this one Topaz - translations on Headless is hard!

**Pull request merged**
